-- Supabase schema for the novel record app.
-- Run this manually in the Supabase SQL Editor.

create table if not exists public.authors (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, id),
  unique (user_id, name)
);

create table if not exists public.novels (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  author_id bigint not null,
  cp_category text not null,
  ending text not null,
  status text not null,
  rating text not null,
  read_count integer not null default 0 check (read_count >= 0),
  notes text not null default '',
  cover text not null default 'book',
  favorite boolean not null default false,
  created_at date not null default current_date,
  updated_at date not null default current_date,
  foreign key (user_id, author_id) references public.authors(user_id, id)
);

create table if not exists public.characters (
  id bigint generated by default as identity primary key,
  novel_id bigint not null references public.novels(id) on delete cascade,
  name text not null,
  attribute text not null,
  sort_order integer not null default 0
);

create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, id),
  unique (user_id, name)
);

create table if not exists public.novel_tags (
  novel_id bigint not null references public.novels(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  primary key (novel_id, tag_id)
);

create index if not exists idx_authors_user_id on public.authors(user_id);
create index if not exists idx_authors_name on public.authors(name);
create index if not exists idx_novels_user_id on public.novels(user_id);
create index if not exists idx_novels_author_id on public.novels(author_id);
create index if not exists idx_novels_updated_at on public.novels(updated_at desc, id desc);
create index if not exists idx_characters_novel_id on public.characters(novel_id);
create index if not exists idx_tags_user_id on public.tags(user_id);
create index if not exists idx_tags_name on public.tags(name);
create index if not exists idx_novel_tags_tag_id on public.novel_tags(tag_id);

alter table public.authors enable row level security;
alter table public.novels enable row level security;
alter table public.characters enable row level security;
alter table public.tags enable row level security;
alter table public.novel_tags enable row level security;

drop policy if exists "authors are owned by the current user" on public.authors;
create policy "authors are owned by the current user"
on public.authors
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "novels are owned by the current user" on public.novels;
create policy "novels are owned by the current user"
on public.novels
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "tags are owned by the current user" on public.tags;
create policy "tags are owned by the current user"
on public.tags
for all
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "characters belong to current user's novels" on public.characters;
create policy "characters belong to current user's novels"
on public.characters
for all
to authenticated
using (
  exists (
    select 1
    from public.novels
    where novels.id = characters.novel_id
      and novels.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.novels
    where novels.id = characters.novel_id
      and novels.user_id = auth.uid()
  )
);

drop policy if exists "novel tags belong to current user's novels" on public.novel_tags;
create policy "novel tags belong to current user's novels"
on public.novel_tags
for all
to authenticated
using (
  exists (
    select 1
    from public.novels
    where novels.id = novel_tags.novel_id
      and novels.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.novels
    where novels.id = novel_tags.novel_id
      and novels.user_id = auth.uid()
  )
  and exists (
    select 1
    from public.tags
    where tags.id = novel_tags.tag_id
      and tags.user_id = auth.uid()
  )
);
